export const ROUTE_POSTS = 'posts'
export const ROUTE_POST = 'post'
export const ROUTE_POST_EDIT = 'post-edit'
export const ROUTE_POST_ADD = 'post-add'
export const ROUTE_AUTHORS = 'authors'
export const ROUTE_AUTHOR = 'author'
