name: pr-sanity-check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn

      - name: Lint check
        run: |
          yarn lint
